#!/usr/bin/env node
/* NS Design System — CSS bundle build.
   =========================================================================
   Flattens styles.css (tokens + base + icon font + component layer) into a
   single distributable stylesheet, and emits a minified twin.

   Why a prebuilt bundle at all, when both consumers run their own bundler:
   the Ghost theme's gulp pipeline concatenates plain CSS and does not resolve
   @import across a node_modules boundary, so handing it one flat file removes
   an entire class of "works in Next, broken in Ghost" bugs. The Next.js app
   can import either the bundle or styles.css directly — same bytes.

   Deliberately NOT run through Tailwind: this bundle is framework-neutral
   plain CSS so it can be dropped into a page with no build step at all
   (Ghost code injection, a CodePen, a static prototype). Tailwind consumers
   additionally import tokens/tailwind.css, which is generated separately.

   Run:  node scripts/build-css.mjs
   CI:   node scripts/build-css.mjs --check   (exits 1 if dist/ is stale) */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";
import atImport from "postcss-import";
import cssnano from "cssnano";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = join(ROOT, "styles.css");
const check = process.argv.includes("--check");

const banner = (min) => `/*! NS Design System — design tokens + component layer${min ? " (minified)" : ""}
 * Generated by scripts/build-css.mjs from styles.css. Do not edit.
 * Consumed by the Ghost theme and the Next.js LMS; both render the same
 * .ns-* classes so a component is one thing with two renderers.
 * MIT © Swarnil Singhai
 */
`;

const source = readFileSync(ENTRY, "utf8");

/* postcss-import inlines the @import graph, so @font-face URLs authored
   relative to their own file must be rewritten to stay correct from dist/. */
const rebaseUrls = {
  postcssPlugin: "ns-rebase-urls",
  Declaration(decl) {
    if (!decl.value.includes("url(")) return;
    // Only the font files' relative hops need rewriting; data: URIs, absolute
    // paths and bare filenames are left exactly as they are. Text fonts live
    // in typography/ (tokens/fonts.css says ../typography/ — already right
    // from dist/, one level deep either way); the Phosphor icon fonts sit
    // beside icons/phosphor.css (./phosphor-*.woff2 → ../icons/ from dist/).
    decl.value = decl.value.replace(/url\((['"]?)\.\/(phosphor[^'")]+)/g, "url($1../icons/$2");
  },
};

const expanded = await postcss([atImport(), rebaseUrls]).process(source, { from: ENTRY, to: join(ROOT, "dist/namaste-ui.css") });
const minified = await postcss([cssnano({ preset: ["default", {
  // Comments are stripped, but the banner is kept — it is the only place the
  // license travels with the file when someone pastes it into Ghost.
  discardComments: { remove: (c) => !c.startsWith("!") },
  // Custom property names must never be mangled: they ARE the public API,
  // and both products reference them by name at runtime.
  reduceIdents: false,
}] })]).process(banner(true) + expanded.css, { from: undefined });

mkdirSync(join(ROOT, "dist"), { recursive: true });

const outputs = [
  ["dist/namaste-ui.css", banner(false) + expanded.css],
  ["dist/namaste-ui.min.css", minified.css],
];

let stale = false;
for (const [rel, content] of outputs) {
  const path = join(ROOT, rel);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === content) continue;
  if (check) { console.error(`STALE: ${rel} — run \`npm run build:css\``); stale = true; continue; }
  writeFileSync(path, content);
  const kb = (Buffer.byteLength(content) / 1024).toFixed(1);
  console.log(`wrote ${rel}  (${kb} kB)`);
}
if (check && stale) process.exit(1);
if (check) console.log("dist/ up to date");
