#!/usr/bin/env node
/* NS Design System — CSS bundle build.
   =========================================================================
   Flattens styles.css (tokens + base + icon font + component layer) into a
   single distributable stylesheet, and emits a minified twin.

   Why a prebuilt bundle at all, when both consumers run their own bundler:
   the Ghost theme's gulp pipeline concatenates plain CSS and does not resolve
   @import across a node_modules boundary, so handing it one flat file removes
   an entire class of "works in Next, broken in Ghost" bugs. The Next.js app
   can import either the bundle or styles.css directly — same bytes.

   TWO bundles come out of here, and the difference matters:

     dist/nsds.css          styles.css only. Framework-neutral plain CSS
                                  with no Tailwind, so it can be dropped into a
                                  page with no build step at all (Ghost code
                                  injection, a CodePen, a static prototype).
                                  This is what Ghost and the Next.js LMS take —
                                  they bring their OWN Tailwind and their own
                                  content globs, so shipping ours would give
                                  them a second preflight and a second copy of
                                  every utility.

     dist/nsds.tailwind.css tailwind.entry.css — Tailwind v4 + the design
                                  system, layered so utilities win. This is what
                                  every page in THIS repo loads, which is why a
                                  Tailwind class works on the styleguide.

   Both are emitted minified too. Layer order (theme, base, ns-components,
   components, utilities) is declared in the entry files, not here.

   Run:  node scripts/build-css.mjs
   CI:   node scripts/build-css.mjs --check   (exits 1 if dist/ is stale) */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";
import atImport from "postcss-import";
import cssnano from "cssnano";
import tailwindcss from "@tailwindcss/postcss";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = join(ROOT, "src/styles.css");
const TW_ENTRY = join(ROOT, "src/tailwind.css");
const check = process.argv.includes("--check");

const banner = (min) => `/*! NS Design System — design tokens + component layer${min ? " (minified)" : ""}
 * Generated by scripts/build-css.mjs from styles.css. Do not edit.
 * Consumed by the Ghost theme and the Next.js LMS; both render the same
 * .ns-* classes so a component is one thing with two renderers.
 * MIT © Swarnil Singhai
 */
`;

const twBanner = (min) => `/*! NS Design System + Tailwind v4${min ? " (minified)" : ""}
 * Generated by scripts/build-css.mjs from tailwind.entry.css. Do not edit.
 * Layer order: theme, base, ns-components, components, utilities — so a
 * Tailwind utility always beats a .ns-* default without !important.
 * Ghost/Next.js should NOT use this file; they import styles.css +
 * tokens/tailwind.css alongside their own Tailwind. See docs/INTEGRATION.md.
 * MIT © Swarnil Singhai
 */
`;

const source = readFileSync(ENTRY, "utf8");

/* postcss-import inlines the @import graph, so @font-face URLs authored
   relative to their own file must be rewritten to stay correct from dist/. */
const rebaseUrls = {
  postcssPlugin: "ns-rebase-urls",
  Declaration(decl) {
    if (!decl.value.includes("url(")) return;
    // Only the font files' relative hops need rewriting; data: URIs, absolute
    // paths and bare filenames are left exactly as they are. Text fonts live
    // in fonts/ (tokens/fonts.css says ../fonts/ — already right from
    // dist/, one level deep either way); the Phosphor icon fonts sit
    // beside icons/phosphor.css (./phosphor-*.woff2 → ../icons/ from dist/).
    decl.value = decl.value.replace(/url\((['"]?)\.\/(phosphor[^'")]+)/g, "url($1../icons/$2");
  },
};

/* Tailwind resolves url() against the ENTRY file (tailwind.entry.css, at the
   repo root), so tokens/fonts.css's `../fonts/x.woff2` comes out as
   `./fonts/x.woff2`. Correct from the root, broken from dist/ — one hop back. */
const rebaseFromRoot = {
  postcssPlugin: "ns-rebase-urls-from-root",
  Declaration(decl) {
    if (!decl.value.includes("url(")) return;
    decl.value = decl.value.replace(/url\((['"]?)\.\/(fonts|icons)\//g, "url($1../$2/");
  },
};

const minify = (css) => postcss([cssnano({ preset: ["default", {
  // Comments are stripped, but the banner is kept — it is the only place the
  // license travels with the file when someone pastes it into Ghost.
  discardComments: { remove: (c) => !c.startsWith("!") },
  // Custom property names must never be mangled: they ARE the public API,
  // and both products reference them by name at runtime.
  reduceIdents: false,
}] })]).process(css, { from: undefined });

const expanded = await postcss([atImport(), rebaseUrls]).process(source, { from: ENTRY, to: join(ROOT, "dist/nsds.css") });
const minified = await minify(banner(true) + expanded.css);

/* Tailwind's plugin resolves its own @import graph, so postcss-import is not in
   this chain — running both would inline the same files twice. rebaseUrls still
   runs after it, for the same reason as above: @font-face URLs are authored
   relative to icons/ and have to survive the move into dist/. */
const twExpanded = await postcss([tailwindcss(), rebaseFromRoot]).process(readFileSync(TW_ENTRY, "utf8"), {
  from: TW_ENTRY,
  to: join(ROOT, "dist/nsds.tailwind.css"),
});
const twMinified = await minify(twBanner(true) + twExpanded.css);

mkdirSync(join(ROOT, "dist"), { recursive: true });

const outputs = [
  ["dist/nsds.css", banner(false) + expanded.css],
  ["dist/nsds.min.css", minified.css],
  ["dist/nsds.tailwind.css", twBanner(false) + twExpanded.css],
  ["dist/nsds.tailwind.min.css", twMinified.css],
];

let stale = false;
for (const [rel, content] of outputs) {
  const path = join(ROOT, rel);
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === content) continue;
  if (check) { console.error(`STALE: ${rel} — run \`npm run build:css\``); stale = true; continue; }
  writeFileSync(path, content);
  const kb = (Buffer.byteLength(content) / 1024).toFixed(1);
  console.log(`wrote ${rel}  (${kb} kB)`);
}
if (check && stale) process.exit(1);
if (check) console.log("dist/ up to date");
