#!/usr/bin/env python3
"""NS Design System — Phosphor subsetter.

Regenerates icons/phosphor.css, icons/phosphor-subset.woff2 and
icons/phosphor-fill-subset.woff2 from the upstream @phosphor-icons/web
package, carrying ONLY the glyphs this repo actually references.

Why a subset at all: the full Phosphor regular face is ~700KB per weight and
we ship two weights. The ~140 glyphs the system uses come to ~20KB. That is
the whole argument, and it is worth the extra build step.

Why this script had to come back: without it, "add an icon" had no correct
answer. The previous session's answer was icons/icons-gap.css — 31 glyphs
redrawn by hand as inline-SVG masks, kept in sync with Phosphor's grid by
eye. That file is deleted; this script replaces it. An icon is now one
class, one source, one regeneration.

WHAT IS USED is not decided here. `node scripts/check-icons.mjs --list`
owns that definition, and this script shells out to it, so the gate that
fails the build and the generator that satisfies it can never disagree
about which glyphs matter.

Prerequisites:
    npm install                      # brings in @phosphor-icons/web
    pip install fonttools brotli     # brotli is what writes woff2

Run:
    python3 scripts/subset-icons.py
    npm run build && npm run check
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UPSTREAM = ROOT / "node_modules" / "@phosphor-icons" / "web"
OUT_DIR = ROOT / "icons"

# (upstream subdir, output woff2 name, css font-family, class that selects it)
FACES = [
    ("regular", "phosphor-subset.woff2", "Phosphor", ".ph"),
    ("fill", "phosphor-fill-subset.woff2", "Phosphor-Fill", ".ph-fill"),
]

HEADER = """/* ============================================================================
   phosphor.css — GENERATED by scripts/subset-icons.py. Do not edit by hand.
   ----------------------------------------------------------------------------
   Phosphor v{version}, subsetted to only the glyphs this repo references and
   served from our own origin. The glyph list comes from
   `node scripts/check-icons.mjs --list`, so it is the same list the build
   gate checks against.

   To add an icon: use the class, then re-run `python3 scripts/subset-icons.py`
   and commit the regenerated icons/. check-icons.mjs FAILS the build on a
   `ph-` class with no glyph, because a missing glyph renders as empty space —
   an invisible control, not a broken one.

   ONE HAND-EDIT IS BAKED IN, not applied afterwards: upstream sets
   `font-family: ... !important` on .ph and .ph-fill. An !important in a lower
   layer beats a normal declaration in a higher one, so it defeated every
   font-* utility a consuming app wrote. It is also unnecessary — .ph and
   .ph-fill are never used on the same element, so they never compete. The
   generator below simply does not emit it.
   ========================================================================== */
"""

FACE_RULES = """
@font-face {{
  font-family: "{family}";
  src: url("./{woff2}") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}}

{selector} {{
  font-family: "{family}";
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  display: inline-block;
}}
"""


def die(message: str) -> "None":
    print(f"\n  subset-icons: {message}\n", file=sys.stderr)
    raise SystemExit(1)


def used_glyphs() -> list[str]:
    """Ask check-icons.mjs what the repo references. One definition, not two."""
    proc = subprocess.run(
        ["node", str(ROOT / "scripts" / "check-icons.mjs"), "--list"],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        die(f"check-icons.mjs --list failed:\n{proc.stderr}")
    names = sorted({line.strip() for line in proc.stdout.splitlines() if line.strip()})
    if not names:
        die("check-icons.mjs --list returned nothing — refusing to write an empty subset.")
    return names


def codepoints(face: str) -> dict[str, int]:
    """name -> codepoint, read out of the upstream stylesheet for that weight."""
    css_path = UPSTREAM / "src" / face / "style.css"
    if not css_path.exists():
        die(f"{css_path} not found. Run `npm install` first — @phosphor-icons/web is a devDependency.")
    css = css_path.read_text(encoding="utf8")
    pairs = re.findall(
        r"\.ph(?:-fill)?\.(ph-[a-z0-9-]+):before\s*\{\s*content:\s*\"\\([0-9a-fA-F]+)\"",
        css,
    )
    return {name: int(code, 16) for name, code in pairs}


def upstream_version() -> str:
    import json

    pkg = UPSTREAM / "package.json"
    if not pkg.exists():
        die("@phosphor-icons/web is not installed. Run `npm install`.")
    return json.loads(pkg.read_text(encoding="utf8"))["version"]


def main() -> None:
    try:
        from fontTools import subset  # noqa: F401
    except ImportError:
        die("fontTools is not installed. Run `pip install fonttools brotli`.")

    names = used_glyphs()
    version = upstream_version()
    print(f"subset-icons: {len(names)} glyph(s) referenced, Phosphor v{version}")

    css_parts = [HEADER.format(version=version)]

    for face, woff2_name, family, selector in FACES:
        table = codepoints(face)
        unknown = [n for n in names if n not in table]
        if unknown:
            die(
                f"{len(unknown)} name(s) are not Phosphor glyphs in the {face} weight:\n    "
                + "\n    ".join(unknown)
                + "\n\n  Fix the typo in the markup, or pick a glyph that exists."
            )

        ttf = UPSTREAM / "src" / face / (
            "Phosphor.ttf" if face == "regular" else "Phosphor-Fill.ttf"
        )
        out = OUT_DIR / woff2_name
        wanted = sorted(table[n] for n in names)

        subset.main([
            str(ttf),
            "--output-file=" + str(out),
            "--flavor=woff2",
            "--unicodes=" + ",".join(f"U+{c:04X}" for c in wanted),
            "--layout-features=",
            "--no-hinting",
            "--desubroutinize",
            "--drop-tables+=DSIG",
        ])
        print(f"  {face:8} → icons/{woff2_name}  ({out.stat().st_size // 1024}KB)")

        css_parts.append(FACE_RULES.format(family=family, woff2=woff2_name, selector=selector))
        css_parts.append(
            "\n".join(
                f'{selector}.{n}:before {{ content: "\\{table[n]:04x}"; }}' for n in names
            )
            + "\n"
        )

    (OUT_DIR / "phosphor.css").write_text("".join(css_parts), encoding="utf8")
    print(f"  css      → icons/phosphor.css ({len(names)} rules per face)")
    print("\n  Now run: npm run build && npm run check")


if __name__ == "__main__":
    main()
